apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cosy-postgres
spec:
  serviceName: "cosy-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: cosy-postgres
  template:
    metadata:
      labels:
        app: cosy-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "cosydb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cosy-postgresql-credentials
                  key: postgresql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cosy-postgresql-credentials
                  key: postgresql-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: cosy-postgres-pvc
